# permissions for end users to view weebles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weeble-viewer-role
rules:
- apiGroups:
  - pogo.demo.com
  resources:
  - weebles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pogo.demo.com
  resources:
  - weebles/status
  verbs:
  - get
